spring.application.name=demo
spring.datasource.password=r4fmx4gjd0
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/worklink_database
spring.jpa.hibernate.ddl-auto=update
server.port=8000
worklink.jwt.secret=Gc/K5VBtbe1i9CywErKyH39J5NOFOwIH59xX0IBNL8k=