spring.application.name=demo
spring.datasource.password=r4fmx4gjd0
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/worklink_database
spring.jpa.hibernate.ddl-auto=update
server.port=8000
